### ISSUE TITLE
Issues with Sign up and Login

### ISSUE THREAD

**Issue by arpitashekhar** [Aishwarya2/RoommateFinder#1]
1. Unable to sign in/sign up.
2. Test email verification functionality.
3. Redirection to the application.

**Comment by Aishwarya2** [comment]
There is no issue with signup. The app has not been deployed yet. So, email verification works only with localhost for now.  Therefore, signup works only in my system as I implemented that.

Use this credential for signing in:
username: asundar2
password: Macrohard*123

Redirection naturally works after that.

**Comment by arpitashekhar** [comment]
Cool!
