### ISSUE TITLE
Create Landing Page

### ISSUE THREAD

**Issue by arpitashekhar** [Aishwarya2/RoommateFinder#2]
After login, the application should redirect to the landing page.

**Comment by Aishwarya2** [comment]
Already fixed in the latest commit. Sign in with username: asundar2, password: Macrohard*123. The landing page is the Create Profile page

**Comment by arpitashekhar** [comment]
Reopening - need to create a separate landing page UI.

**Comment by varoteamulya** [comment]
The landing page has been created
