### ISSUE TITLE
Implement search functionality

### ISSUE THREAD

**Issue by arpitashekhar** [Aishwarya2/RoommateFinder#3]
By default, display results according to the entered budget and location preference.
Filter results according to the selected tags.

**Comment by arpitashekhar** [comment]
Displaying default search results based on current users locality.

**Comment by arpitashekhar** [comment]
Search by locality and food preference is now working.

**Comment by Aishwarya2** [comment]
Feature: Previous search results are displayed. Works properly now

**Comment by Aishwarya2** [comment]
Enbaled searching by gender

**Comment by patel-bhavik** [comment]
Completed the code and committed to repo.
